dubbo:
  application:
    name: privider
  registry:
    id: zookeeper
    address: 127.0.0.1 # zookeeper注册中心的地址
    port: 2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
    host: 127.0.0.1
  scan:
    base-packages: com.hyz.service.impl
server:
  port: 8081